from __future__ import annotations

from pathlib import Path
from typing import Iterable

AUTO_SECTION_START = '<!-- BEGIN AUTO-GENERATED DOC LIST -->'
AUTO_SECTION_END = '<!-- END AUTO-GENERATED DOC LIST -->'
INVENTORY_RELATIVE_PATH = Path('docs/generated/doc-inventory.md')


def read_text(path: Path) -> str:
    return path.read_text(encoding='utf-8')


def write_text_if_changed(path: Path, content: str) -> bool:
    if path.exists() and read_text(path) == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding='utf-8')
    return True


def extract_title_and_summary(path: Path) -> tuple[str, str | None]:
    title = path.stem.replace('-', ' ').replace('_', ' ').title()
    summary: str | None = None
    for raw_line in read_text(path).splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line.startswith('#'):
            heading = line.lstrip('#').strip()
            if heading:
                title = heading
            continue
        if line.startswith('<!--'):
            continue
        summary = line
        break
    return title, summary


def iter_markdown_files(directory: Path) -> Iterable[Path]:
    for path in sorted(directory.glob('*.md')):
        if path.name == 'index.md':
            continue
        yield path


def build_index_entries_markdown(section_dir: Path, repo_root: Path) -> str:
    entries: list[str] = []
    for path in iter_markdown_files(section_dir):
        title, summary = extract_title_and_summary(path)
        relative_link = path.relative_to(section_dir).as_posix()
        entry = f'- [{path.name}]({relative_link}) — {title}'
        if summary:
            entry += f' — {summary}'
        entries.append(entry)
    if not entries:
        return '- 現在登録済みのドキュメントはありません。'
    return '\n'.join(entries)


def replace_auto_section(text: str, replacement: str) -> str:
    if AUTO_SECTION_START not in text or AUTO_SECTION_END not in text:
        raise ValueError('Managed section markers are missing.')
    start_index = text.index(AUTO_SECTION_START) + len(AUTO_SECTION_START)
    end_index = text.index(AUTO_SECTION_END)
    return f"{text[:start_index]}\n{replacement}\n{text[end_index:]}"


def render_index_file(path: Path, section_dir: Path, repo_root: Path) -> str:
    return replace_auto_section(read_text(path), build_index_entries_markdown(section_dir, repo_root))


def relative_link(from_path: Path, to_path: Path) -> str:
    return to_path.relative_to(from_path.parent).as_posix() if to_path.is_relative_to(from_path.parent) else Path(
        Path(*([ '..' ] * len(from_path.parent.relative_to(from_path.anchor).parts)))
    ).as_posix()


def build_inventory_markdown(repo_root: Path) -> str:
    inventory_path = repo_root / INVENTORY_RELATIVE_PATH
    lines = [
        '# Documentation inventory',
        '',
        '> This file is generated by `python scripts/doc_gardening.py`. Do not edit it manually.',
        '',
        '## Root knowledge map',
    ]

    for relative in [
        Path('README.md'),
        Path('ARCHITECTURE.md'),
        Path('COMMAND.md'),
        Path('docs/DOCUMENTATION_SYSTEM.md'),
        Path('docs/QUALITY_SCORE.md'),
    ]:
        path = repo_root / relative
        if not path.exists():
            continue
        title, summary = extract_title_and_summary(path)
        link = Path('../..') / relative if relative.parts[0] != 'docs' else Path('..') / relative.relative_to('docs')
        entry = f'- [{relative.name}]({link.as_posix()}) — {title}'
        if summary:
            entry += f' — {summary}'
        lines.append(entry)

    lines.extend(['', '## docs/ tree'])
    docs_root = repo_root / 'docs'
    for section in sorted(path for path in docs_root.iterdir() if path.is_dir() and path.name != 'generated'):
        lines.append(f'- `{section.relative_to(repo_root).as_posix()}/`')
        for doc in iter_markdown_files(section):
            title, summary = extract_title_and_summary(doc)
            link = Path('..') / doc.relative_to(docs_root)
            entry = f'  - [{doc.name}]({link.as_posix()}) — {title}'
            if summary:
                entry += f' — {summary}'
            lines.append(entry)
        index_path = section / 'index.md'
        if index_path.exists():
            title, summary = extract_title_and_summary(index_path)
            link = Path('..') / index_path.relative_to(docs_root)
            entry = f'  - [{index_path.name}]({link.as_posix()}) — {title}'
            if summary:
                entry += f' — {summary}'
            lines.append(entry)
        for subsection in sorted(path for path in section.iterdir() if path.is_dir()):
            lines.append(f'  - `{subsection.relative_to(repo_root).as_posix()}/`')
            subsection_index = subsection / 'index.md'
            if subsection_index.exists():
                title, summary = extract_title_and_summary(subsection_index)
                link = Path('..') / subsection_index.relative_to(docs_root)
                entry = f'    - [{subsection_index.name}]({link.as_posix()}) — {title}'
                if summary:
                    entry += f' — {summary}'
                lines.append(entry)
            for doc in iter_markdown_files(subsection):
                title, summary = extract_title_and_summary(doc)
                link = Path('..') / doc.relative_to(docs_root)
                entry = f'    - [{doc.name}]({link.as_posix()}) — {title}'
                if summary:
                    entry += f' — {summary}'
                lines.append(entry)

    generated_root = docs_root / 'generated'
    if generated_root.exists():
        lines.extend(['', '## Generated docs'])
        for doc in sorted(generated_root.glob('*.md')):
            title, summary = extract_title_and_summary(doc)
            link = doc.relative_to(generated_root)
            entry = f'- [{doc.name}]({link.as_posix()}) — {title}'
            if summary:
                entry += f' — {summary}'
            lines.append(entry)

    workflows_root = repo_root / '.github' / 'workflows'
    if workflows_root.exists():
        lines.extend(['', '## GitHub Actions'])
        for workflow in sorted(workflows_root.glob('*.yml')):
            link = Path('../..') / workflow.relative_to(repo_root)
            lines.append(f'- [{workflow.name}]({link.as_posix()})')

    return '\n'.join(lines) + '\n'


def expected_managed_files(repo_root: Path) -> dict[Path, str]:
    docs_root = repo_root / 'docs'
    managed: dict[Path, str] = {
        docs_root / 'design-docs' / 'index.md': render_index_file(
            docs_root / 'design-docs' / 'index.md',
            docs_root / 'design-docs',
            repo_root,
        ),
        docs_root / 'product-specs' / 'index.md': render_index_file(
            docs_root / 'product-specs' / 'index.md',
            docs_root / 'product-specs',
            repo_root,
        ),
        docs_root / 'exec-plans' / 'active' / 'index.md': render_index_file(
            docs_root / 'exec-plans' / 'active' / 'index.md',
            docs_root / 'exec-plans' / 'active',
            repo_root,
        ),
        docs_root / 'exec-plans' / 'completed' / 'index.md': render_index_file(
            docs_root / 'exec-plans' / 'completed' / 'index.md',
            docs_root / 'exec-plans' / 'completed',
            repo_root,
        ),
        repo_root / INVENTORY_RELATIVE_PATH: build_inventory_markdown(repo_root),
    }
    return managed


def synchronize_docs(repo_root: Path) -> list[Path]:
    changed: list[Path] = []
    for path, content in expected_managed_files(repo_root).items():
        if write_text_if_changed(path, content):
            changed.append(path)
    return changed


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    changed = synchronize_docs(repo_root)
    if changed:
        print('Updated documentation artifacts:')
        for path in changed:
            print(f'- {path.relative_to(repo_root).as_posix()}')
    else:
        print('Documentation artifacts are already up to date.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
